# Religious affiliation data

First, clone locally the repository:

   ```git clone https://github.com/dsl2l2017/lecture_2```

There is a dataset in this repository called ``data.all.csv``. This dataset contains the following variables:

* ``id``: Respondent id number	
* ``year``: Gss year for this respondent	
* ``relig``: Rs religious preference	
* ``god``: Rs confidence in the existence of god	
* ``age``: Age of respondent	
* ``cohort``: Year of birth	
* ``sex``: Respondents sex	
* ``race``: Race of respondent	

The definition of the different variables is in the [```questionnaire.txt``` file](https://github.com/dsl2l2017/lecture_2/blob/master/questionnaire.txt) in this repository.

In [1]:
%pylab inline
import numpy as np
import pandas as pd  # just for loading the data

# jus to make plots bigger
plt.rcParams['figure.figsize'] = (1 * 10.0, 1 * 9.0)
plt.rcParams['font.size'] = 30

Populating the interactive namespace from numpy and matplotlib

# 1. Religious affiliation, by year

Generate a plot that shown the religious affiliation as a function of the year of survey. Consider the religions Protestant, Catholic, None (atheist) and group all the rest into  'Other'.

Suggestion: 
* See the dataset description to understand what the different numerical values correspond to.
* Use the Numpy methods we saw in the last lecture.
* Use [Matplotlib](https://matplotlib.org/users/pyplot_tutorial.html) to plot the result.

In [2]:
RELIGIONS = {0: 'IAP', 1: 'PROTESTANT', 2: 'CATHOLIC', 3: 'JEWISH', 4: 'NONE', 
            5: 'OTHER', 6: 'BUDDHISM', 7: 'HINDUISM', 8: 'OTHER EASTERN', 9: 'MOSLEM/ISLAM',
            10: 'ORTHODOX-CHRISTIAN', 11: 'CHRISTIAN', 12: 'NATIVE AMERICAN', 13: 'INTER-NONDENOMINATIONAL'}

df = pd.read_csv('data.all.csv')
df

,CASEID,YEAR,AGE,SEX,RACE,HISPANIC,RELIG,COHORT,BIRTHMO,PARELIG,PAYRBORN,MARELIG,MAYRBORN
0,1,1972,23,2,1,0,3,1949,0,0,0,0,0
1,2,1972,70,1,1,0,2,1902,0,0,0,0,0
2,3,1972,48,2,1,0,1,1924,0,0,0,0,0
3,4,1972,27,2,1,0,5,1945,0,0,0,0,0
4,5,1972,61,2,1,0,1,1911,0,0,0,0,0
5,6,1972,26,1,1,0,1,1946,0,0,0,0,0
6,7,1972,28,1,1,0,2,1944,0,0,0,0,0
7,8,1972,27,1,1,0,3,1945,0,0,0,0,0
8,9,1972,21,2,2,0,1,1951,0,0,0,0,0
9,10,1972,30,2,2,0,1,1942,0,0,0,0,0
10,11,1972,30,2,2,0,1,1942,0,0,0,0,0
11,12,1972,56,1,2,0,1,1916,0,0,0,0,0
12,13,1972,54,1,2,0,1,1918,0,0,0,0,0
13,14,1972,49,2,2,0,1,1923,0,0,0,0,0
14,15,1972,41,1,2,0,1,1931,0,0,0,0,0
15,16,1972,54,1,2,0,1,1918,0,0,0,0,0
16,17,1972,24,1,1,0,1,1948,0,0,0,0,0
17,18,1972,62,2,1,0,1,1910,0,0,0,0,0
18,19,1972,46,2,1,0,1,1926,0,0,0,0,0
19,20,1972,21,2,1,0,1,1951,0,0,0,0,0
20,21,1972,57,1,1,0,1,1915,0,0,0,0,0
21,22,1972,58,1,1,0,1,1914,0,0,0,0,0
22,23,1972,21,1,1,0,1,1951,0,0,0,0,0
23,24,1972,26,2,1,0,1,1946,0,0,0,0,0
24,25,1972,71,2,1,0,1,1901,0,0,0,0,0
25,26,1972,53,2,1,0,2,1919,0,0,0,0,0
26,27,1972,42,1,1,0,1,1930,0,0,0,0,0
27,28,1972,42,2,1,0,1,1930,0,0,0,0,0
28,29,1972,20,1,1,0,1,1952,0,0,0,0,0
29,30,1972,23,1,1,0,1,1949,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55057,55058,2010,50,2,2,1,4,1960,0,0,0,0,0
55058,55059,2010,71,1,1,2,2,1939,0,0,0,0,0
55059,55060,2010,19,1,1,2,2,1991,0,0,0,0,0
55060,55061,2010,19,1,3,2,1,1991,0,0,0,0,0
55061,55062,2010,44,1,3,2,2,1966,0,0,0,0,0
55062,55063,2010,76,2,1,1,1,1934,0,0,0,0,0
55063,55064,2010,70,1,1,1,1,1940,0,0,0,0,0
55064,55065,2010,30,1,3,2,1,1980,0,0,0,0,0
55065,55066,2010,39,2,1,1,4,1971,0,0,0,0,0
55066,55067,2010,42,2,1,1,2,1968,0,0,0,0,0
55067,55068,2010,25,1,1,1,1,1985,0,0,0,0,0
55068,55069,2010,62,2,1,1,2,1948,0,0,0,0,0
55069,55070,2010,65,1,1,1,4,1945,0,0,0,0,0
55070,55071,2010,49,2,1,1,1,1961,0,0,0,0,0
55071,55072,2010,69,2,1,1,4,1941,0,0,0,0,0
55072,55073,2010,43,2,1,1,1,1967,0,0,0,0,0
55073,55074,2010,36,1,1,1,4,1974,0,0,0,0,0
55074,55075,2010,34,1,1,1,4,1976,0,0,0,0,0
55075,55076,2010,43,2,1,1,4,1967,0,0,0,0,0
55076,55077,2010,48,2,1,1,1,1962,0,0,0,0,0
55077,55078,2010,23,1,1,1,1,1987,0,0,0,0,0
55078,55079,2010,67,2,1,1,1,1943,0,0,0,0,0
55079,55080,2010,21,2,1,1,1,1989,0,0,0,0,0
55080,55081,2010,70,1,3,1,2,1940,0,0,0,0,0
55081,55082,2010,63,1,1,1,1,1947,0,0,0,0,0
55082,55083,2010,62,1,1,1,1,1948,0,0,0,0,0
55083,55084,2010,66,2,1,1,1,1944,0,0,0,0,0
55084,55085,2010,54,2,1,1,2,1956,0,0,0,0,0
55085,55086,2010,57,2,1,1,4,1953,0,0,0,0,0
55086,55087,2010,30,1,1,1,4,1980,0,0,0,0,0

In [3]:
# convert to numpy array
A = df.values
cols = df.columns.values

# 2. Religious affiliation, by year of birth

Generate a plot that shown the religious affiliation as a function of the year of birth. Consider only only data taken between 2006 and 2016 and people born after 1990. Consider the religions Protestant, Catholic, None (atheist) and group all the rest into  'Other'.

In [ ]:
df = pd.read_csv('data.all.csv')
A = df.values
cols = df.columns.values

## 3. Is there a difference between men and women?

Test whether there is a significant difference in "religiousness" between men and women. You can consider that a "religious" person is everyone who did not consider himself of religion 'none'. Is the difference statistically significant?

Hint: Do you remember how Fisher solved the lady tasting tea problem?

In [35]:
df = pd.read_csv('data.all.csv')
A = df.values
cols = df.columns.values

MALE = 1
FEMALE = 2